config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  #Home Screen
  root  'static_pages#home'

  #Static Pages
  get   'contact'     => 'contacts#new'
  get   'blog'        => 'posts#index'
  get   'portfolio'   => 'projects#index'


  resources :posts
  resources :contacts
  resources :projects

  #Users Resource
  resources :users


  get '*path' => redirect('/')

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  after_create :send_notification
  def send_notification
    ContactMailer.new_contact(self).deliver
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
	extend FriendlyId
	friendly_id :title, use: :slugged
end

app/models/project.rb
class Project < ActiveRecord::Base
	extend FriendlyId
	friendly_id :title, use: :slugged

  has_attached_file :image, styles: { large: "1280x1280>", medium: "300x300>", thumb: "200x200#" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  has_attached_file :logoimage, styles: { medium: "300x300>", thumb: "200x200>" }
  validates_attachment_content_type :logoimage, content_type: /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :authenticate_admin!, except: [:new, :create]
  def new
    @contact = Contact.new
  end
  def create
    @contact = Contact.new post_params

    if @contact.save
      redirect_to root_path, notice: "Message successfully saved and sent"
    else
      render 'new', notice: "Something went awry.  I was unable to save the contact."
    end
  end
  def index
    @contacts = Contact.all.order("created_at desc").paginate(page: params[:page], per_page: 10)
  end
  private
    def post_params
      params.require(:contact).permit(:name, :email, :message)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :find_post, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_admin!, except: [:index, :show]
	def index
		@posts = Post.all.order("created_at desc").paginate(page: params[:page], per_page: 10)
	end
	def show

	end
	def new
		@post = Post.new
	end
	def create
		@post = Post.new post_params
		respond_to do |format|
			if @post.save
				format.html { redirect_to @post, notice: "Post successfully saved and stored" }
				format.json { render :show, status: :created, location: @post }
			else
				format.html { render 'new', notice: "Something went awry.  I was unable to save post." }
				format.json { render json: @post.errors, status: :unprocessable_entity }
			end
		end
	end
	def destroy
		@post.destroy
		respond_to do |format|
			format.html { redirect_to posts_path, notice: "The Post was successfully deleted!" }
			format.json { head :no_content } 
		end
	end
	def edit

	end
	def update
		respond_to do |format|
			if @post.update post_params
				format.html { redirect_to @post, notice: "Post updated!" }
				format.json { render :show, status: :ok, location: @post }
			else
				format.html { render 'edit' }
				format.json { render json: @post.errors, status: :unprocessable_entity }
			end
		end
	end
	private
		def post_params
			params.require(:post).permit(:title, :content, :slug)
		end
		def find_post
			@post = Post.friendly.find(params[:id])
		end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	before_action :find_project, only: [:show, :update, :edit, :destroy]
	before_action :authenticate_admin!, except: [:index, :show]

	def index
		@projects = Project.all.order("created_at desc").paginate(page: params[:page], per_page: 5)
	end
	def show

	end
	def new
		@project = Project.new
	end
	def create
		@project = Project.new project_params

		if @project.save
			redirect_to @project, notice: "New Project saved!"
		else
			render 'new'
		end
	end
	def edit

	end
	def update
		if @project.update project_params
			redirect_to @project, notice: "Project updated properly"
		else
			render 'edit'
		end
	end
	def destroy
		@project.destroy
		redirect_to projects_path
	end


	private
		def find_project
			@project = Project.friendly.find(params[:id])
		end
		def project_params
			params.require(:project).permit(:title, :description, :link, :slug, :image, :logoimage)
		end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	@instagram = Instagram.user_recent_media("219769686", {:count => 6})

  	client = Twitter::REST::Client.new do |config|
		  config.consumer_key        = ENV['twit_consumer_key']
		  config.consumer_secret     = ENV['twit_consumer_secret']
		  config.access_token        = ENV['twit_access_token']
		  config.access_token_secret = ENV['twit_access_token_secret']
		end

  	@tweets = client.user_timeline("Kaytal1", :count => 5)
  		respond_to do |format|
  			format.html # index.html.erb
  			format.json { render :json => @posts }
  		end
  end

  def contact
  	
  end
end

app/helpers/application_helper.rb
require 'twitter-text'
module ApplicationHelper
  class HTMLwithPygments < Redcarpet::Render::HTML
    def block_code(code, language)
      Pygments.highlight(code, lexer: language)
    end
  end
	# Returns the full title on a per-page basis.
	def full_title(page_title = '')
		base_title = "Josh Bryant | Web Developer"
		if page_title.empty?
			base_title
		else
			base_title + " | " + page_title
		end
	end

	#Twitter Text helper
	include Twitter::Autolink
 
  def twitter_text(text)
    text = auto_link(text)
    text ? text.html_safe : ''
  end

  def markdown(content)
  	renderer = HTMLwithPygments.new(hard_wrap: true, filter_html: true)
  	options = {
  		autolink: true,
  		no_intra_emphasis: true,
  		disable_indented_code_blocks: true,
  		fenced_code_blocks: true,
  		lax_html_blocks: true,
  		strikethrough: true,
  		superscript: true
  	}
  	Redcarpet::Markdown.new(renderer, options).render(content).html_safe
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/contacts/index.html.erb
<div id="<%= controller.controller_name %>_<%= controller.action_name %>">
  <h1 class="text-center">Contact Forms</h1>
  <hr class="post-hr"/>
  <div class="row">
    <% @contacts.each do |contact| %>
      <h2><%= contact.created_at.strftime('%A, %B %d, %Y') %></h2>
      <table class="table">
        <thead>
          <tr>
            <th>Attribute</th>
            <th>Value</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Name</td>
            <td><%= contact.name %></td>
          </tr>
          <tr>
            <td>Email</td>
            <td><%= contact.email %></td>
          </tr>
          <tr>
            <td>Message</td>
            <td><%= contact.message %></td>
          </tr>
        </tbody>
      </table>
    <% end %>
  </div>
  <div class="row">
    <%= will_paginate @posts %>
  </div>
</div>

app/views/contacts/new.html.erb
<div class="row">
  <div class="col-sm-8 col-sm-offset-2">
  <h1 class="text-center">Contact Me!</h1>
  <p class="text-center">Wanna chat? Want me to work with you?  Want me to work for you?</p>
  <%= form_for @contact do |f| %>
    <% if @contact.errors.any? %>
      <h2><%= pluralize(@contact.errors.count, "error" ) %> prevented this contact from saving:</h2>
      <ul>
        <% @contact.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    <% end%>
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
    <%= f.label :email %>
    <%= f.text_field :email, class: "form-control" %>
    <%= f.label :message %>
    <%= f.text_area :message, class: "form-control" %>
    <%= f.submit 'Submit', class: "btn btn-primary" %>
  <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
 	<meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= favicon_link_tag 'favicon.png', type: 'image/png' %>
  <title><%= full_title(yield(:title)) %></title>
  <%= google_webfonts_link_tag :crimson_text			=> [400, 600, 700] %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "shared/header" %>

  <%= render "shared/mainnav" %>

  <main class="container">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
  	<%= yield %>
  </main>

  	<%= render "shared/footer" %>

  <%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/posts/_disqus.html.erb
<div id="disqus_thread"></div>
<script>
/**
* RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
* LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables
*/

	var disqus_config = function () {
	this.page.url = '<%= url_for([@post, {only_path: false}]) %>'; // Replace PAGE_URL with your page's canonical URL variable
	this.page.identifier = '<%= @post.id %>'; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
	this.page.title = '<%= @post.title %>';
	};
	
(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');

s.src = '//joshbryantme.disqus.com/embed.js';

s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
	<% if @post.errors.any? %>
		<h2><%= pluralize(@post.errors.count, "error" ) %> prevented this post from saving:</h2>
		<ul>
			<% @post.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
	<% end%>
	<%= f.label :title %>
	<%= f.text_field :title, class: "form-control" %>
	<%= f.label :content, "Write your article here:" %>
	<%= f.text_area :content, class: "form-control" %>
	<%= f.submit 'Submit', class: "btn btn-primary" %>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<div id="<%= controller.controller_name %>_<%= controller.action_name %>">
	<h1 class="text-center">Blog Posts</h1>
	<hr class="post-hr"/>
	<div class="row">
		<% @posts.each do |post| %>
			<article class="col-sm-8 col-sm-offset-2 single-post">
				<header>
					<h1 class="text-center">
						<%= link_to post.title, post_path(post) %>
						<br>
						<small class="date"><%= post.created_at.strftime('%A, %B %d, %Y') %></small>
					</h1>
				</header>
				<div class="single-post-exerpt">
					<%= markdown(post.content) %>
				</div>
			</article>
		<% end %>
	</div>
	<div class="row">
		<%= will_paginate @posts %>
	</div>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'shared/form' %>

app/views/posts/show.html.erb
<article>
	<header>
		<h1 class="text-center">
			<%= @post.title %><br />
			<small class="date"><%= @post.created_at.strftime('%A, %B %d') %></small>
		</h1>
		<hr class="post-hr">
	</header>
	<div class="row">
		<div class="col-sm-8 col-sm-offset-2 post"><%= markdown(@post.content) %></div>
	</div>
	<div classs="row">
		<hr class="post-hr">
		<div class="col-sm-8 col-sm-offset-2 text-center" id="share">
			<h2>Share</h2>
			<a onclick="javascript:window.open('http://twitter.com/share?text=<%= @post.title %> by @kaytal1 - &amp;url=<%= url_for([@post, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);"><i class="fa fa-twitter"></i></a>
			<a onclick="javascript:window.open('http://facebook.com/sharer.php?u=<%= url_for([@post, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);"><i class="fa fa-facebook"></i></a>
			<a onclick="javascript:window.open('https://plus.google.com/share?url=<%= url_for([@post, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);"><i class="fa fa-google-plus"></i></a>
		</div>
	</div>
	</div>
	<footer class="row">
		<% if admin_signed_in? %>
			<div class="col-sm-12">
				<p class="text-center"><%= link_to "Edit", edit_post_path(@post), class: 'btn' %> <%= link_to "Delete", post_path(@post), method: :delete, data: {confirm: "Are you sure you want to delete this post?"}, class: 'btn' %></p>
			</div>
		<% end %>
	</footer>
	<%= render 'disqus' %>
</article>

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
	<% if @project.errors.any? %>
		<h2><%= pluralize(@project.errors.count, "error" ) %> prevented this project from saving:</h2>
		<ul>
			<% @project.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
	<% end%>
	<%= f.label :title %>
	<%= f.text_field :title, class: "form-control" %>
	<%= f.label "Logo Image" %>
	<%= f.file_field :logoimage, class: "form-control" %>
	<%= f.label :image %>
	<%= f.file_field :image, class: "form-control" %>
	<%= f.label :description %>
	<%= f.text_area :description, class: "form-control" %>
	<%= f.label :link %>
	<%= f.text_field :link, class: "form-control" %>
	<%= f.submit %>
<% end %>

app/views/projects/edit.html.erb
<h1>Edit Project</h1>
<div class="row">
	<div class="col-sm-8 col-sm-offset-2">
		<%= render 'form' %>
	</div>
</div>

app/views/projects/index.html.erb
<h1 class="text-center">Projects</h1>

<div class="row">
	<% @projects.each do |project| %>
		<article class="col-sm-6 col-sm-offset-3 single-project">
			<header>
				<h1 class="text-center">
					<%= link_to project.title, project_path(project) %>
				</h1>
			</header>
			<%= image_tag project.logoimage.url(:thumb), class: 'img-responsive img-center' %>
			<div class="single-project-desc">
				<%= project.description %>
			</div>
		</article>
	<% end %>
</div>
<div class="row">
	<%= will_paginate @projects %>
</div>

app/views/projects/new.html.erb
<h1>New Project</h1>
<div class="row">
	<div class="col-sm-8 col-sm-offset-2">
		<%= render 'form' %>
	</div>
</div>

app/views/projects/show.html.erb
<article>
  <header>
    <h1 class="text-center">
      <%= @project.title %><br />
    </h1>
    <hr>
  </header>
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2"><%= markdown(@project.description) %></div>
  </div>
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2 text-center">
      <a href="<%= @project.link %>" class="project_button" target="_blank">Visit <%= @project.title %></a>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <%= image_tag @project.image.url, class: 'img-responsive' %>
    </div>
  </div>
  <footer class="row">
    <div class="col-sm-12">
      <p class="text-center"><%= link_to "Edit", edit_project_path(@project), class: 'btn' %> <%= link_to "Delete", project_path(@project), method: :delete, data: {confirm: "Are you sure you want to delete this project?"}, class: 'btn' %></p>
    </div>
  </footer>
</article>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
	<div class="text-center">
		<ul>
			<li>&copy; Copyright <%= Date.today.year %> - Josh Bryant</li>
			<li><a href="https://www.twitter.com/kaytal1" target="_blank"><i class="fa fa-twitter"></i> Twitter</a></li>
			<li><a href="https://instagram.com/kaytal1" target="_blank"><i class="fa fa-instagram"></i> Instagram</a></li>
			<li><a href="http://www.southernfriedgeek.com" target="_blank">Southern Fried Geek</a></li>
	</div>
</footer>

app/views/shared/_header.html.erb
<header class="main-header">
	<div class="header-portrait">
		<div class="avatar">
			<%= link_to image_tag("avatar-425.jpg", class: 'img-responsive img-circle'), root_path %>
		</div>
	</div>
</header>

app/views/shared/_mainnav.html.erb
<nav>
	<ul>
		<li><%= link_to 'Blog', blog_path %></li>
		<li><%= link_to 'Portfolio', portfolio_path %></li>
		<li><%= link_to 'Contact', contact_path %></li>
		<% if admin_signed_in? %>
			<li><%= link_to 'Log Out', destroy_admin_session_path %></li>
		<% end %>
	</ul>
</nav>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>

<% #remove this bit when the form and other pages are built #%>
<header>
	<h2 class="text-center">Josh Bryant<br /><small>Greater Memphis Area, TN, MS, AR</small></h2>
</header>
<section class="row">
	<div class="col-sm-6 col-sm-offset-3">
		<p class="text-center">I am a web developer who dabbles in Rails.  I love being outside and crafting things with wood.  I am married to my best friend and I could not be happier.</p>
	</div>
</section>
<h1 class="text-center">Coming Soon!</h1>

app/views/static_pages/home.html.erb
<header>
	<h2 class="text-center">Josh Bryant<br /><small>Greater Memphis Area, TN, MS, AR</small></h2>
</header>
<section class="row">
	<div class="col-sm-6 col-sm-offset-3">
		<p class="text-center">I am a web developer who dabbles in Rails.  I love being outside and crafting things with wood.  I am married to my best friend and I could not be happier.</p>
	</div>
</section>
<section class="social row">
	<h2>Social</h2>
	<div class="row">
		<div class="col-sm-6 instagram-row">
			<div class="instagram row">
				<div class="col-sm-12"><h3>Instagram</h3></div>
				<% @instagram.each do |instagram| %>
					<div class="col-sm-6 insta-indiv">
						<a href="<%= instagram.link %>" target="_blank">
							<%= image_tag instagram.images.standard_resolution.url, :class => "img-responsive" %>
						</a>
					</div>
				<% end %>
			</div>
		</div>
		<div class="col-sm-6">
			<div class="twitter col-sm-12">
				<h3>Twitter</h3>
				<% @tweets.each do |t| %>
				<article class="tweet row">
					<div class="col-sm-2 col-xs-12">
						<% if t.retweeted_status? %>
							<%= image_tag(t.retweeted_status.user.profile_image_url, class: "img-responsive twitter-prof-img", alt: t.retweeted_status.user.screen_name) %>
						<% else %>
							<%= image_tag(t.user.profile_image_url, class: "img-responsive twitter-prof-img", alt: t.user.screen_name) %>
						<% end %>
					</div>
					<div class="col-sm-10 col-xs-12">
						<% if t.retweeted_status? %>
							<h1><%= t.retweeted_status.user.name %> <small><%=  link_to "@#{t.retweeted_status.user.screen_name}", "#{t.retweeted_status.user.url}" %></small></h1>
							<p>Retweeted: '<%= twitter_text(t.retweeted_status.text) %>'</p>
						<% else %>
							<h1><%= t.user.name %> <small><%=  link_to "@#{t.user.screen_name}", "#{t.user.url}" %></small></h1>
							<p>Tweeted: '<%= twitter_text(t.text) %>'</p>
						<% end %>
						<%= link_to(raw('Read on Twitter <i class="fa fa-external-link"></i>'), "#{t.url}", target: "_blank") %> 
					</div>
				</article>
				<% end %>
			</div>
		</div>
	</div>
</section>